// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConfirmableController from "./confirmable_controller.js"
application.register("confirmable", ConfirmableController)

import DismissableController from "./dismissable_controller.js"
application.register("dismissable", DismissableController)

import DropdownController from "./dropdown_controller.js"
application.register("dropdown", DropdownController)

import ToggleableController from "./toggleable_controller.js"
application.register("toggleable", ToggleableController)
