// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConfirmableController from "./confirmable_controller.js"
application.register("confirmable", ConfirmableController)

import DismissableController from "./dismissable_controller.js"
application.register("dismissable", DismissableController)

import DropdownController from "./dropdown_controller.js"
application.register("dropdown", DropdownController)

import FadeOutFlashController from "./fade_out_flash_controller.js"
application.register("fade-out-flash", FadeOutFlashController)

import NeutralConfirmableController from "./neutral_confirmable_controller.js"
application.register("neutral-confirmable", NeutralConfirmableController)

import Portions__FoodSearchController from "./portions/food_search_controller.js"
application.register("portions--food-search", Portions__FoodSearchController)

import Portions__PortionSelectController from "./portions/portion_select_controller.js"
application.register("portions--portion-select", Portions__PortionSelectController)

import ToggleableController from "./toggleable_controller.js"
application.register("toggleable", ToggleableController)
