---

plugins:
- rubocop-minitest
- rubocop-rails
- rubocop-rake
- rubocop-capybara

AllCops:
  Exclude:
  - bin/**/*
  - db/schema.rb
  - tmp/**/*

Rails:
  Enabled: true

Capybara/ClickLinkOrButtonStyle:
  Enabled: true
  EnforcedStyle: strict

Capybara/FindAllFirst:
  Enabled: true

Capybara/MatchStyle:
  Enabled: true

Capybara/NegationMatcher:
  Enabled: true

Capybara/NegationMatcherAfterVisit:
  Enabled: true

Capybara/RSpec/HaveSelector:
  Enabled: true

Capybara/RSpec/PredicateMatcher:
  Enabled: true

Capybara/RedundantWithinFind:
  Enabled: true

Capybara/SpecificActions:
  Enabled: true

Capybara/SpecificFinders:
  Enabled: true

Capybara/SpecificMatcher:
  Enabled: true

Gemspec/AddRuntimeDependency:
  Enabled: true

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Gemspec/DevelopmentDependencies:
  Enabled: true

Gemspec/RequireMFA:
  Enabled: true

Layout/BeginEndAlignment:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/LineContinuationLeadingSpace:
  Enabled: true

Layout/LineContinuationSpacing:
  Enabled: true

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Layout/LineLength:
  Max: 120

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true

Lint/AmbiguousOperatorPrecedence:
  Enabled: true

Lint/AmbiguousRange:
  Enabled: true

Lint/ArrayLiteralInRegexp:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: true

Lint/ConstantOverwrittenInRescue:
  Enabled: true

Lint/ConstantReassignment:
  Enabled: true

Lint/CopDirectiveSyntax:
  Enabled: true

Lint/DeprecatedConstants:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateMagicComment:
  Enabled: true

Lint/DuplicateMatchPattern:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/DuplicateRequire:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/DuplicateSetElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/EmptyFile:
  Enabled: true

Lint/EmptyInPattern:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/HashNewWithKeywordArgumentsAsDefault:
  Enabled: true

Lint/IdentityComparison:
  Enabled: true

Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true

Lint/ItWithoutArgumentsInBlock:
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/LiteralAssignmentInCondition:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/MixedCaseRange:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/NonAtomicFileOperation:
  Enabled: true

Lint/NumberedParameterAssignment:
  Enabled: true

Lint/NumericOperationWithConstantResult:
  Enabled: true

Lint/OrAssignmentToConstant:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/RedundantDirGlobSort:
  Enabled: true

Lint/RedundantRegexpQuantifiers:
  Enabled: true

Lint/RedundantTypeConversion:
  Enabled: true

Lint/RefinementImportMethods:
  Enabled: true

Lint/RequireRangeParentheses:
  Enabled: true

Lint/RequireRelativeSelfPath:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/SharedMutableDefault:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/SuppressedExceptionInNumberConversion:
  Enabled: true

Lint/SymbolConversion:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Lint/TripleQuotes:
  Enabled: true

Lint/UnescapedBracketInRegexp:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/UselessConstantScoping:
  Enabled: true

Lint/UselessDefaultValueArgument:
  Enabled: true

Lint/UselessDefined:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: true

Lint/UselessNumericOperation:
  Enabled: true

Lint/UselessOr:
  Enabled: true

Lint/UselessRescue:
  Enabled: true

Lint/UselessRuby2Keywords:
  Enabled: true

Lint/UselessTimes:
  Enabled: true

Metrics/BlockLength:
  Exclude:
  - config/environments/*.rb
  - config/routes.rb

Metrics/ClassLength:
  Exclude:
  - test/**/*_test.rb

Metrics/CollectionLiteralLength:
  Enabled: true

Metrics/MethodLength:
  Exclude:
  - app/services/nutrition_facts/journal_days.rb
  - app/services/nutrition_facts/meal_ingredients.rb
  - app/services/nutrition_facts/meals.rb
  - app/services/nutrition_facts/portions.rb
  - app/services/nutrition_facts/recipe_ingredients.rb
  - app/services/nutrition_facts/recipes.rb
  - app/services/vegan_detection/journal_day.rb
  - app/services/vegan_detection/recipe.rb
  - db/archive/migrate/*
  - db/migrate/*

Minitest/AssertInDelta:
  Enabled: true

Minitest/AssertKindOf:
  Enabled: true

Minitest/AssertOperator:
  Enabled: true

Minitest/AssertOutput:
  Enabled: true

Minitest/AssertPathExists:
  Enabled: true

Minitest/AssertPredicate:
  Enabled: true

Minitest/AssertRaisesCompoundBody:
  Enabled: true

Minitest/AssertRaisesWithRegexpArgument:
  Enabled: true

Minitest/AssertSame:
  Enabled: true

Minitest/AssertSilent:
  Enabled: true

Minitest/AssertWithExpectedArgument:
  Enabled: true

Minitest/AssertionInLifecycleHook:
  Enabled: true

Minitest/DuplicateTestRun:
  Enabled: true

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: true

Minitest/Focus:
  Enabled: true

Minitest/LifecycleHooksOrder:
  Enabled: true

Minitest/LiteralAsActualArgument:
  Enabled: true

Minitest/MultipleAssertions:
  Enabled: false

Minitest/NonExecutableTestMethod:
  Enabled: true

Minitest/NonPublicTestMethod:
  Enabled: true

Minitest/RedundantMessageArgument:
  Enabled: true

Minitest/RefuteInDelta:
  Enabled: true

Minitest/RefuteKindOf:
  Enabled: true

Minitest/RefuteOperator:
  Enabled: true

Minitest/RefutePathExists:
  Enabled: true

Minitest/RefutePredicate:
  Enabled: true

Minitest/RefuteSame:
  Enabled: true

Minitest/ReturnInTestMethod:
  Enabled: true

Minitest/SkipEnsure:
  Enabled: true

Minitest/SkipWithoutReason:
  Enabled: true

Minitest/TestFileName:
  Enabled: true

Minitest/TestMethodName:
  Enabled: true

Minitest/UnreachableAssertion:
  Enabled: true

Minitest/UnspecifiedException:
  Enabled: true

Minitest/UselessAssertion:
  Enabled: true

Naming/BlockForwarding:
  Enabled: true

Naming/PredicateMethod:
  Enabled: true

Rails/ActionControllerFlashBeforeRender:
  Enabled: true

Rails/ActionControllerTestCase:
  Enabled: true

Rails/ActionOrder:
  Enabled: true

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/ActiveSupportOnLoad:
  Enabled: true

Rails/AddColumnIndex:
  Enabled: true

Rails/AfterCommitOverride:
  Enabled: true

Rails/AttributeDefaultBlockValue:
  Enabled: true

Rails/CompactBlank:
  Enabled: true

Rails/DangerousColumnNames:
  Enabled: true

Rails/DeprecatedActiveModelErrorsMethods:
  Enabled: true

Rails/DotSeparatedKeys:
  Enabled: true

Rails/DuplicateAssociation:
  Enabled: true

Rails/DuplicateScope:
  Enabled: true

Rails/DurationArithmetic:
  Enabled: true

Rails/EagerEvaluationLogMessage:
  Enabled: true

Rails/EnumSyntax:
  Enabled: true

Rails/EnvLocal:
  Enabled: true

Rails/EnvironmentVariableAccess:
  Enabled: true
  AllowReads: true

Rails/ExpandedDateRange:
  Enabled: true

Rails/FindById:
  Enabled: true

Rails/FreezeTime:
  Enabled: true

Rails/I18nLazyLookup:
  Enabled: true

Rails/I18nLocaleAssignment:
  Enabled: true

Rails/I18nLocaleTexts:
  Enabled: true

Rails/IgnoredColumnsAssignment:
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/MigrationClassName:
  Enabled: true

Rails/MultipleRoutePaths:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/Pluck:
  Enabled: true

Rails/PluckId:
  Enabled: true

Rails/PluckInWhere:
  Enabled: true

Rails/RedundantActiveRecordAllMethod:
  Enabled: true

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: true

Rails/RedundantTravelBack:
  Enabled: true

Rails/RenderInline:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/ResponseParsedBody:
  Enabled: true

Rails/RootJoinChain:
  Enabled: true

Rails/RootPathnameMethods:
  Enabled: true

Rails/RootPublicPath:
  Enabled: true

Rails/SelectMap:
  Enabled: true

Rails/ShortI18n:
  Enabled: true

Rails/SquishedSQLHeredocs:
  Enabled: true

Rails/StripHeredoc:
  Enabled: true

Rails/StrongParametersExpect:
  Enabled: true

Rails/ThreeStateBooleanColumn:
  Enabled: true

Rails/TimeZoneAssignment:
  Enabled: true

Rails/ToFormattedS:
  Enabled: true

Rails/ToSWithArgument:
  Enabled: true

Rails/TopLevelHashWithIndifferentAccess:
  Enabled: true

Rails/TransactionExitStatement:
  Enabled: true

Rails/UnusedIgnoredColumns:
  Enabled: true

Rails/UnusedRenderContent:
  Enabled: true

Rails/WhereEquals:
  Enabled: true

Rails/WhereExists:
  Enabled: true

Rails/WhereMissing:
  Enabled: true

Rails/WhereNot:
  Enabled: true

Rails/WhereNotWithMultipleConditions:
  Enabled: true

Rails/WhereRange:
  Enabled: true

Security/CompoundHash:
  Enabled: true

Security/IoMethods:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/AmbiguousEndlessMethodDefinition:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/ArrayIntersect:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/BitwisePredicate:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/CollectionCompact:
  Enabled: true

Style/CombinableDefined:
  Enabled: true

Style/CombinableLoops:
  Enabled: true

Style/ComparableBetween:
  Enabled: true

Style/ComparableClamp:
  Enabled: true

Style/ConcatArrayLiterals:
  Enabled: true

Style/DataInheritance:
  Enabled: true

Style/DigChain:
  Enabled: true

Style/DirEmpty:
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/EmptyHeredoc:
  Enabled: true

Style/EmptyStringInsideInterpolation:
  Enabled: true

Style/EndlessMethod:
  Enabled: true

Style/EnvHome:
  Enabled: true

Style/ExactRegexpMatch:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/FetchEnvVar:
  Enabled: true

Style/FileEmpty:
  Enabled: true

Style/FileNull:
  Enabled: true

Style/FileRead:
  Enabled: true

Style/FileTouch:
  Enabled: true

Style/FileWrite:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashConversion:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/HashFetchChain:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashSlice:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IfWithBooleanLiteralBranches:
  Enabled: true

Style/InPatternThen:
  Enabled: true

Style/ItAssignment:
  Enabled: true

Style/ItBlockParameter:
  Enabled: true

Style/KeywordArgumentsMerging:
  Enabled: true

Style/KeywordParametersOrder:
  Enabled: true

Style/Lambda:
  Enabled: false

Style/MagicCommentFormat:
  Enabled: true

Style/MapCompactWithConditionalBlock:
  Enabled: true

Style/MapIntoArray:
  Enabled: true

Style/MapToHash:
  Enabled: true

Style/MapToSet:
  Enabled: true

Style/MinMaxComparison:
  Enabled: true

Style/MultilineInPatternThen:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/NestedFileDirname:
  Enabled: true

Style/NilLambda:
  Enabled: true

Style/NumberedParameters:
  Enabled: true

Style/NumberedParametersLimit:
  Enabled: true

Style/ObjectThen:
  Enabled: true

Style/OpenStructUse:
  Enabled: true

Style/OperatorMethodCall:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/QuotedSymbols:
  Enabled: true

Style/RedundantArgument:
  Enabled: true

Style/RedundantArrayConstructor:
  Enabled: true

Style/RedundantArrayFlatten:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantConstantBase:
  Enabled: true

Style/RedundantCurrentDirectoryInPath:
  Enabled: true

Style/RedundantDoubleSplatHashBraces:
  Enabled: true

Style/RedundantEach:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantFilterChain:
  Enabled: true

Style/RedundantFormat:
  Enabled: true

Style/RedundantHeredocDelimiterQuotes:
  Enabled: true

Style/RedundantInitialize:
  Enabled: true

Style/RedundantInterpolationUnfreeze:
  Enabled: true

Style/RedundantLineContinuation:
  Enabled: true

Style/RedundantRegexpArgument:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpConstructor:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantSelfAssignment:
  Enabled: true

Style/RedundantSelfAssignmentBranch:
  Enabled: true

Style/RedundantStringEscape:
  Enabled: true

Style/ReturnNilInPredicateMethodDefinition:
  Enabled: true

Style/SafeNavigationChainLength:
  Enabled: true

Style/SelectByRegexp:
  Enabled: true

Style/SendWithLiteralMethodName:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/SingleLineDoEndBlock:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/SoleNestedConditional:
  Enabled: true

Style/StringChars:
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SuperArguments:
  Enabled: true

Style/SuperWithArgsParentheses:
  Enabled: true

Style/SwapValues:
  Enabled: true

Style/SymbolArray:
  Enabled: false

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Style/YAMLFileRead:
  Enabled: true
