---

- name: "Install rbenv for {{ app_user }}"
  git:
    repo: "https://github.com/rbenv/rbenv.git"
    dest: "~{{ app_user }}/.rbenv"
    accept_hostkey: yes
    clone: yes
    force: yes
  become: yes
  become_user: "{{ app_user }}"

- name: "Install rbenv plugins for {{ app_user }}"
  git:
    repo: "https://github.com/rbenv/{{ item }}.git"
    dest: "~{{ app_user }}/.rbenv/plugins/{{ item }}"
    accept_hostkey: yes
    clone: yes
    force: yes
  with_items:
    - "ruby-build"
    - "rbenv-vars"
    - "rbenv-gem-rehash"
  remote_user: "{{ app_user }}"
  become: yes
  become_user: "{{ app_user }}"

- name: "Install rbenv loader"
  template:
    src: "rbenv.sh.j2"
    dest: "/etc/profile.d/rbenv_{{ app_user }}.sh"
  become: yes
