---

- name: "Install dependencies for compiling Ruby"
  become: yes
  apt:
    pkg: "{{ item }}"
    state: "present"
  with_items:
    - "build-essential"
    - "g++"
    - "gcc"
    - "libffi6"
    - "libffi-dev"
    - "libyaml-0-2"
    - "libyaml-dev"
    - "make"
    - "openssl"
    - "libssl-dev"
    - "libreadline6"
    - "libreadline-dev"
    - "libbz2-1.0"
    - "libbz2-dev"

- name: "Install Ruby {{ app_ruby_version }} for {{ app_user }}"
  command: "~{{ app_user }}/.rbenv/bin/rbenv install {{ app_ruby_version }}"
  args:
    creates: "~{{ app_user }}/.rbenv/versions/{{ app_ruby_version }}"
  become: yes
  become_user: "{{ app_user }}"

- name: "Set global Ruby {{ app_ruby_version }}"
  copy:
    dest: "~{{ app_user }}/.rbenv/version"
    content: "{{ app_ruby_version }}"
    owner: "{{ app_user }}"
    group: "{{ app_user_group }}"
  become: yes
  become_user: "{{ app_user }}"