---

- name: "Install ufw firewall manager"
  become: "yes"
  apt:
    pkg: "ufw"
    state: "present"

- name: "Firewall allows ssh"
  become: "yes"
  ufw:
    rule: "allow"
    proto: "tcp"
    port: "ssh"

- name: "Firewall allows http"
  become: "yes"
  ufw:
    rule: "allow"
    proto: "tcp"
    port: "http"

- name: "Firewall allows https"
  become: "yes"
  ufw:
    rule: "allow"
    proto: "tcp"
    port: "https"

- name: "Firewall enable"
  become: "yes"
  ufw:
    state: "enabled"
    policy: "allow"

- name: "Enable and start ufw"
  become: "yes"
  service:
    name: "ufw"
    enabled: "yes"
    state: "started"
