---

- name: "Create app user group"
  become: yes
  group:
    name: "{{ app_user_group }}"
    state: "present"

- name: "Create app user"
  become: yes
  user:
    name: "{{ app_user }}"
    group: "{{ app_user_group }}"
    groups: "www-data"
    shell: "/bin/bash"

- name: "Set authorized_key for app_user"
  become: yes
  authorized_key:
    user: "{{ app_user }}"
    state: present
    key: "{{ public_keys }}"
  when: "public_keys is defined"

- name: "Set private keys for app_user"
  become: yes
  copy:
    dest: "{{ item['path'] }}"
    content: "{{ item['content'] }}"
    owner: "{{ app_user }}"
    group: "{{ app_user_group }}"
    mode: 0600
  no_log: True
  with_items: "{{ private_keys }}"

