---

- name: "Clone code"
  git:
    repo: "{{ github_repo }}"
    dest: "{{ app_application_dir }}"
    version: "{{ prompted_deploy_branch }}"
    clone: yes
    accept_hostkey: True
    force: yes
    key_file: ""
  become: yes
  become_user: "{{ app_user }}"
  when: playbook == "provision"

- name: "Update code"
  git:
    repo: "{{ github_repo }}"
    dest: "{{ app_application_dir }}"
    version: "{{ prompted_deploy_branch }}"
    clone: no
    update: yes
    force: yes
  become: yes
  become_user: "{{ app_user }}"
  when: playbook == "deploy"
