---

- name: "Create the app database (provision only)"
  postgresql_db:
    name: "{{ app_database_name }}"
    state: present
  become_user: "postgres"
  become: yes
  when: "playbook == 'provision'"

- name: "Create the database user (provision only)"
  postgresql_user:
    name: "{{ app_database_username }}"
    password: "{{ app_database_password }}"
    role_attr_flags: "CREATEDB,NOSUPERUSER"
    db: "{{ app_database_name }}"
    state: "present"
  become_user: "postgres"
  become: yes
  with_items:
    - 127.0.0.1
    - localhost
  when: "playbook == 'provision'"

- name: "Load database schema (provision only)"
  shell: "~{{ app_user }}/.rbenv/shims/bundle exec rake db:schema:load"
  args:
    chdir: "{{ app_application_dir }}"
  become: yes
  become_user: "{{ app_user }}"
  when: "playbook == 'provision' and prompted_recreate_database == 'yes'"

- name: "Migrate database"
  command: "~{{ app_user }}/.rbenv/shims/bundle exec rake db:migrate"
  args:
    chdir: "{{ app_application_dir }}"
  become: yes
  become_user: "{{ app_user }}"
