---

- name: "Copy the letsencrypt configuration"
  become: yes
  template:
    src: "letsencrypt/letsencrypt_cli.ini.j2"
    dest: "/etc/letsencrypt/{{ item['primary_domains'][0] }}.ini"
    mode: "0600"
  with_items: "{{ app_domains }}"

- include: "nginx_disable_ssl.yml"

- name: "Restart nginx"
  become: yes
  service:
    name: "nginx"
    state: "restarted"

# - name: "Request the certificate"
#   become: yes
#   command: "/opt/certbot/certbot-auto certonly --nginx --force-renewal --expand --noninteractive"

# - include: "nginx_enable_ssl.yml"

# - name: "Restart nginx"
#   become: yes
#   service:
#     name: "nginx"
#     state: "restarted"

