---

- name: "Create nginx sites-available directories"
  become: yes
  file:
    state: directory
    path: "/etc/nginx/sites-available/{{ app_name }}/{{ item['primary_domains'][0] }}"
    owner: "{{ app_user }}"
    group: "{{ app_user_group }}"
    mode: 0755
    recurse: "yes"
  with_items: "{{ app_domains }}"

- name: "Create nginx sites-enabled directories"
  become: yes
  file:
    state: directory
    path: "/etc/nginx/sites-enabled/{{ app_name }}/{{ item['primary_domains'][0] }}"
    owner: "{{ app_user }}"
    group: "{{ app_user_group }}"
    mode: 0755
    recurse: "yes"
  with_items: "{{ app_domains }}"

- name: "Copy upstream.conf"
  become: "yes"
  template:
    src: "nginx/upstream.conf.j2"
    dest: "/etc/nginx/sites-available/{{ app_name }}/upstream.conf"

- name: "Copy ssl-disabled-redirects.conf for all app_domains"
  become: "yes"
  template:
    src: "nginx/ssl-disabled-redirects.conf.j2"
    dest: "/etc/nginx/sites-available/{{ app_name }}/{{ item['primary_domains'][0] }}/ssl-disabled-redirects.conf"
  with_items: "{{ app_domains }}"

- name: "Copy ssl-disabled.conf for all app_domains"
  become: "yes"
  template:
    src: "nginx/ssl-disabled.conf.j2"
    dest: "/etc/nginx/sites-available/{{ app_name }}/{{ item['primary_domains'][0] }}/ssl-disabled.conf"
  with_items: "{{ app_domains }}"

- name: "Copy ssl-enabled-http-to-https-redirects.conf for all app_domains"
  become: "yes"
  template:
    src: "nginx/ssl-enabled-http-to-https-redirects.conf.j2"
    dest: "/etc/nginx/sites-available/{{ app_name }}/{{ item['primary_domains'][0] }}/ssl-enabled-http-to-https-redirects.conf"
  with_items: "{{ app_domains }}"

- name: "Copy ssl-enabled-redirects.conf for all app_domains"
  become: "yes"
  template:
    src: "nginx/ssl-enabled-redirects.conf.j2"
    dest: "/etc/nginx/sites-available/{{ app_name }}/{{ item['primary_domains'][0] }}/ssl-enabled-redirects.conf"
  with_items: "{{ app_domains }}"

- name: "Copy ssl-enabled.conf for all app_domains"
  become: "yes"
  template:
    src: "nginx/ssl-enabled.conf.j2"
    dest: "/etc/nginx/sites-available/{{ app_name }}/{{ item['primary_domains'][0] }}/ssl-enabled.conf"
  with_items: "{{ app_domains }}"

- name: "Disable default website from conf.d"
  become: "yes"
  file:
    path: 
    state: "absent"
  with_items:
    - "/etc/nginx/conf.d/default.conf"
    - "/etc/nginx/sites-available/default"
    - "/var/www/html"
    - "/etc/nginx/sites-enabled/default"

- include: "nginx_disable_ssl.yml"

- name: "Restart nginx"
  become: "yes"
  service:
    name: "nginx"
    state: "restarted"

