---

- hosts: "{{ prompted_environment }}"
  gather_facts: False
  vars_files:
    - "app_vars/app.yml"
  pre_tasks:
    - name: 'install python2'
      raw: "test -e /usr/bin/python || (sudo apt-get update && sudo apt-get -y install python-minimal)"

  vars:
    playbook: "provision"

  vars_prompt:
    - name: "prompted_environment"
      prompt: "Which environment would you like to provision?"
      private: no
    - name: "prompted_recreate_database"
      prompt: "Do you want to recreate the database(s)? (only 'yes' will recreate the database)"
      private: no
    - name: "prompted_deploy_branch"
      prompt: "Branch to deploy"
      default: "master"
      private: no

  roles:
    # - role: "setup_check"
    # - role: "packages"
    # - role: "ufw"
    # - role: "user"
    # - role: "ruby"
    # - role: "redis"
    # - role: "nginx"
    # - role: "letsencrypt"
    - role: "app_deploy"

