env:
  RAILS_ENV: test

name: Continuous Integration
on: [pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Start PostgreSQL
        run: |
          sudo systemctl start postgresql.service
          pg_isready
          sudo -u postgres createuser -s -d -r -w runner

      - uses: actions/checkout@v1

      - uses: ruby/setup-ruby@v1
        with:
           bundler-cache: true

      - name: Setup database
        run: |
          cp ./.github/workflows/templates/database.yml.github-actions config/database.yml
          bin/rails db:test:prepare

      - name: Precompile assets
        run: bin/rails assets:precompile

      - name: bin/test
        run: bin/test
