env:
  NODE_VERSION: 16
  RAILS_ENV: test
  POSTGRES_PASSWORD: "postgres"

name: Continuous Integration
on: [pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v1

      - uses: ruby/setup-ruby@v1
        with:
           bundler-cache: true

      - name: Setup database
        run: |
          cp ./.github/workflows/templates/database.yml.github-actions config/database.yml
          bin/rails db:test:prepare

      - name: Precompile assets
        run: bin/rails assets:precompile

      - name: bin/test
        run: bin/test
